### ISSUE TITLE
Cannot ignore operators

### ISSUE THREAD

**Issue by mseeley** [mseeley/finch#251]
The shift from `off` to `ignore` was incomplete and causing problems.

The stream below throws resolve errors when it encounters ignore.

```
---
- use: "@finch/values"
  params:
    values:
      - Do
      - I
      - dare
      - "/"
      - Disturb
      - the
      - universe?
    delay: 100
- ignore: "@finch/regexp-accept"
  params:
    pattern: "/^(Do|dare|Disturb)$/"
```
